"""
Email Service - Send form summaries via SMTP with PDF and XML attachments.
"""
import io
import smtplib
import xml.etree.ElementTree as ET
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime

from fpdf import FPDF

from app.config import get_settings


async def send_form_email(
    to_email: str,
    subject: str,
    form_data: dict,
    form_type: str = "occurrence",
) -> dict:
    """Send a completed form summary via email with PDF and XML attachments."""
    settings = get_settings()

    if not settings.smtp_user or not settings.smtp_password:
        return {"error": "Email not configured - SMTP credentials missing"}

    html_body = _build_email_html(form_data, form_type)
    pdf_bytes = _build_pdf(form_data, form_type)
    xml_bytes = _build_xml(form_data, form_type)

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = settings.email_from or settings.smtp_user
    msg["To"] = to_email

    # HTML body
    msg.attach(MIMEText(html_body, "html"))

    # PDF attachment
    ref = form_data.get("occurrence_reference", form_data.get("tracking_id", "form"))
    pdf_part = MIMEBase("application", "pdf")
    pdf_part.set_payload(pdf_bytes)
    encoders.encode_base64(pdf_part)
    pdf_part.add_header("Content-Disposition", f"attachment; filename={ref}.pdf")
    msg.attach(pdf_part)

    # XML attachment
    xml_part = MIMEBase("application", "xml")
    xml_part.set_payload(xml_bytes)
    encoders.encode_base64(xml_part)
    xml_part.add_header("Content-Disposition", f"attachment; filename={ref}.xml")
    msg.attach(xml_part)

    try:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)
        return {"success": True, "sent_to": to_email, "attachments": ["pdf", "xml"]}
    except Exception as e:
        return {"error": f"Failed to send email: {e}"}


# ── PDF Generation ────────────────────────────────────────────────

def _build_pdf(form_data: dict, form_type: str) -> bytes:
    """Generate a PDF document from form data."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_font("Helvetica", "B", 18)
    if form_type == "occurrence":
        pdf.cell(0, 12, "EMS Occurrence Report", new_x="LMARGIN", new_y="NEXT", align="C")
    else:
        pdf.cell(0, 12, "Teddy Bear Comfort Program", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "EAI Ambulance Service", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 6, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    # Divider
    pdf.set_draw_color(26, 115, 232)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Fields
    fields = _get_display_fields(form_data, form_type)
    for label, value in fields:
        if value and value != "N/A":
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(60, 7, f"{label}:", new_x="END")
            pdf.set_font("Helvetica", "", 10)
            # Handle long text with multi_cell
            if len(str(value)) > 60:
                pdf.ln()
                pdf.set_x(20)
                pdf.multi_cell(170, 6, str(value))
            else:
                pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.ln(10)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by Para AI Assistant - EAI Ambulance Service", align="C")

    return pdf.output()


# ── XML Generation ────────────────────────────────────────────────

def _build_xml(form_data: dict, form_type: str) -> bytes:
    """Generate an XML document from form data."""
    if form_type == "occurrence":
        root = ET.Element("OccurrenceReport")
        root.set("xmlns", "urn:eai:ambulance:occurrence-report")
    else:
        root = ET.Element("TeddyBearTracking")
        root.set("xmlns", "urn:eai:ambulance:teddy-bear")

    root.set("generated", datetime.utcnow().isoformat() + "Z")
    root.set("service", "EAI Ambulance Service")

    fields = _get_display_fields(form_data, form_type)
    for label, value in fields:
        if value and value != "N/A":
            # Convert label to XML-safe tag name
            tag = label.replace(" ", "").replace("#", "Number").replace("&", "And")
            elem = ET.SubElement(root, tag)
            if isinstance(value, list):
                for item in value:
                    sub = ET.SubElement(elem, "Item")
                    sub.text = str(item)
            else:
                elem.text = str(value)

    tree = ET.ElementTree(root)
    buf = io.BytesIO()
    ET.indent(tree, space="  ")
    tree.write(buf, encoding="utf-8", xml_declaration=True)
    return buf.getvalue()


# ── Shared helpers ────────────────────────────────────────────────

def _get_display_fields(form_data: dict, form_type: str) -> list[tuple[str, str]]:
    """Return ordered (label, value) pairs for display."""
    if form_type == "occurrence":
        return [
            ("Occurrence Reference", form_data.get("occurrence_reference", "N/A")),
            ("Date & Time", form_data.get("incident_date_time", "N/A")),
            ("Classification", form_data.get("classification", "N/A")),
            ("Classification Details", form_data.get("classification_details", "N/A")),
            ("Occurrence Type", form_data.get("occurrence_type", "N/A")),
            ("Call Number", form_data.get("call_number", "N/A")),
            ("Brief Description", form_data.get("brief_description", "N/A")),
            ("Description of Event", form_data.get("description_of_event", "N/A")),
            ("Action Taken", form_data.get("action_taken", "N/A")),
            ("Suggested Resolution", form_data.get("suggested_resolution", "N/A")),
            ("Other Services Involved", form_data.get("other_services_involved", "N/A")),
            ("Service", form_data.get("service", "N/A")),
            ("Vehicle #", form_data.get("vehicle_number", "N/A")),
            ("Vehicle Description", form_data.get("vehicle_description", "N/A")),
            ("Role", form_data.get("role", "N/A")),
            ("Badge #", form_data.get("badge_number", "N/A")),
            ("Report Creator", form_data.get("report_creator", "N/A")),
            ("Requested By", form_data.get("requested_by", "N/A")),
            ("Management Notes", form_data.get("management_notes", "N/A")),
            ("Status", form_data.get("status", "N/A")),
        ]
    else:
        return [
            ("Date & Time", form_data.get("distribution_timestamp", "N/A")),
            ("Recipient Type", form_data.get("recipient_type", "N/A")),
            ("Recipient Age", form_data.get("recipient_age", "N/A")),
            ("Recipient Gender", form_data.get("recipient_gender", "N/A")),
        ]


def _build_email_html(form_data: dict, form_type: str) -> str:
    """Build an HTML email body from form data."""
    if form_type == "occurrence":
        title = "EMS Occurrence Report"
    else:
        title = "Teddy Bear Comfort Program"

    fields = _get_display_fields(form_data, form_type)

    rows = ""
    for label, value in fields:
        if value and value != "N/A":
            rows += f"""
            <tr>
                <td style="padding:8px 12px;border-bottom:1px solid #eee;font-weight:600;color:#333;width:200px;">{label}</td>
                <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#555;">{value}</td>
            </tr>"""

    return f"""
    <html>
    <body style="font-family:Arial,sans-serif;margin:0;padding:20px;background:#f5f5f5;">
        <div style="max-width:600px;margin:0 auto;background:white;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">
            <div style="background:#1a73e8;color:white;padding:20px;">
                <h2 style="margin:0;">{title}</h2>
                <p style="margin:5px 0 0;opacity:0.9;">EAI Ambulance Service - Para AI Assistant</p>
            </div>
            <table style="width:100%;border-collapse:collapse;padding:20px;">
                {rows}
            </table>
            <div style="padding:15px 20px;background:#f9f9f9;font-size:12px;color:#999;">
                Generated by Para AI Assistant | PDF and XML versions attached
            </div>
        </div>
    </body>
    </html>
    """
